# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 王扣扣的个人博客
email: 954014787@qq.com
description: > # this means to ignore newlines until "baseurl:"
  新人入门，请大家多多指教~
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codeit.wang" # the base hostname & protocol for your site
twitter_username: ter9527
github_username:  WaTer9527

# Build settings
markdown: kramdown
